class Company:
    ID = ''
    password = ''
    companyname = ''
    email = ''
    major = ''
    address = ''
    annualsales = ''
    introduce = ''
    web=''
    managername = ''
    managerph = ''
    pfauthority = ''
    pfperiod = ''
    request_authority = 0
